"""Import Roles

Revision ID: 2eeded763d4f
Revises: 6bacb900c2dd
Create Date: 2025-02-06 20:25:11.992724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eeded763d4f'
down_revision: Union[str, None] = '6bacb900c2dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('id_persona', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_cliente_id_cliente'), 'cliente', ['id_cliente'], unique=False)
    op.drop_constraint('cliente_id_cliente_fkey', 'cliente', type_='foreignkey')
    op.create_foreign_key(None, 'cliente', 'persona', ['id_persona'], ['id_persona'])
    op.add_column('empleado', sa.Column('id_persona', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_empleado_id_empleado'), 'empleado', ['id_empleado'], unique=False)
    op.drop_constraint('empleado_id_empleado_fkey', 'empleado', type_='foreignkey')
    op.create_foreign_key(None, 'empleado', 'persona', ['id_persona'], ['id_persona'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'empleado', type_='foreignkey')
    op.create_foreign_key('empleado_id_empleado_fkey', 'empleado', 'persona', ['id_empleado'], ['id_persona'])
    op.drop_index(op.f('ix_empleado_id_empleado'), table_name='empleado')
    op.drop_column('empleado', 'id_persona')
    op.drop_constraint(None, 'cliente', type_='foreignkey')
    op.create_foreign_key('cliente_id_cliente_fkey', 'cliente', 'persona', ['id_cliente'], ['id_persona'])
    op.drop_index(op.f('ix_cliente_id_cliente'), table_name='cliente')
    op.drop_column('cliente', 'id_persona')
    # ### end Alembic commands ###
