"""cHANGE uSER

Revision ID: 476f66852442
Revises: d20a9eb06267
Create Date: 2025-02-06 19:49:22.065784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '476f66852442'
down_revision: Union[str, None] = 'd20a9eb06267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona',
    sa.Column('id_persona', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_persona'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_persona_id_persona'), 'persona', ['id_persona'], unique=False)
    op.drop_constraint('cliente_email_key', 'cliente', type_='unique')
    op.drop_index('ix_cliente_id_cliente', table_name='cliente')
    op.create_foreign_key(None, 'cliente', 'persona', ['id_cliente'], ['id_persona'])
    op.drop_column('cliente', 'telefono')
    op.drop_column('cliente', 'nombre')
    op.drop_column('cliente', 'apellido')
    op.drop_column('cliente', 'email')
    op.drop_index('ix_empleado_id_empleado', table_name='empleado')
    op.create_foreign_key(None, 'empleado', 'persona', ['id_empleado'], ['id_persona'])
    op.drop_column('empleado', 'nombre')
    op.drop_column('empleado', 'rol')
    op.drop_column('empleado', 'apellido')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleado', sa.Column('apellido', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('empleado', sa.Column('rol', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('empleado', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'empleado', type_='foreignkey')
    op.create_index('ix_empleado_id_empleado', 'empleado', ['id_empleado'], unique=False)
    op.add_column('cliente', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('cliente', sa.Column('apellido', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('cliente', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('cliente', sa.Column('telefono', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cliente', type_='foreignkey')
    op.create_index('ix_cliente_id_cliente', 'cliente', ['id_cliente'], unique=False)
    op.create_unique_constraint('cliente_email_key', 'cliente', ['email'])
    op.drop_index(op.f('ix_persona_id_persona'), table_name='persona')
    op.drop_table('persona')
    # ### end Alembic commands ###
