"""Import Roles

Revision ID: 6bacb900c2dd
Revises: 476f66852442
Create Date: 2025-02-06 19:50:32.139711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bacb900c2dd'
down_revision: Union[str, None] = '476f66852442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id_role', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_role')
    )
    op.create_index(op.f('ix_role_id_role'), 'role', ['id_role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_id_role'), table_name='role')
    op.drop_table('role')
    # ### end Alembic commands ###
