"""Add Role to Empleado

Revision ID: a6cd05aa9fd7
Revises: 1f6452e313fb
Create Date: 2025-02-06 20:34:05.620756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6cd05aa9fd7'
down_revision: Union[str, None] = '1f6452e313fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleado', sa.Column('id_rol', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'empleado', 'role', ['id_rol'], ['id_role'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'empleado', type_='foreignkey')
    op.drop_column('empleado', 'id_rol')
    # ### end Alembic commands ###
