"""Init Migration

Revision ID: d20a9eb06267
Revises: 76c1b980ac80
Create Date: 2025-02-06 12:50:29.448036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20a9eb06267'
down_revision: Union[str, None] = '76c1b980ac80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('cedula', sa.String(), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_cliente_id_cliente'), 'cliente', ['id_cliente'], unique=False)
    op.create_table('empleado',
    sa.Column('id_empleado', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_empleado')
    )
    op.create_index(op.f('ix_empleado_id_empleado'), 'empleado', ['id_empleado'], unique=False)
    op.create_table('tipo_lavado',
    sa.Column('id_tipo_lavado', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('precio', sa.DECIMAL(), nullable=False),
    sa.Column('duracion_estimada', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_lavado')
    )
    op.create_index(op.f('ix_tipo_lavado_id_tipo_lavado'), 'tipo_lavado', ['id_tipo_lavado'], unique=False)
    op.create_table('vehiculo',
    sa.Column('id_vehiculo', sa.UUID(), nullable=False),
    sa.Column('placa', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('tipo_vehiculo', sa.String(), nullable=False),
    sa.Column('id_cliente', sa.UUID(), nullable=True),
    sa.Column('total_lavados', sa.Integer(), nullable=True),
    sa.Column('ultima_fecha_lavado', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_vehiculo'),
    sa.UniqueConstraint('placa')
    )
    op.create_index(op.f('ix_vehiculo_id_vehiculo'), 'vehiculo', ['id_vehiculo'], unique=False)
    op.create_table('orden_servicio',
    sa.Column('id_orden', sa.UUID(), nullable=False),
    sa.Column('id_vehiculo', sa.UUID(), nullable=True),
    sa.Column('id_empleado', sa.UUID(), nullable=True),
    sa.Column('fecha_orden', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('total_cobro', sa.DECIMAL(), nullable=False),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleado.id_empleado'], ),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculo.id_vehiculo'], ),
    sa.PrimaryKeyConstraint('id_orden')
    )
    op.create_index(op.f('ix_orden_servicio_id_orden'), 'orden_servicio', ['id_orden'], unique=False)
    op.create_table('historial_lavado',
    sa.Column('id_historial', sa.UUID(), nullable=False),
    sa.Column('id_orden', sa.UUID(), nullable=True),
    sa.Column('id_tipo_lavado', sa.UUID(), nullable=True),
    sa.Column('fecha_lavado', sa.Date(), nullable=False),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('estado_lavado', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_orden'], ['orden_servicio.id_orden'], ),
    sa.ForeignKeyConstraint(['id_tipo_lavado'], ['tipo_lavado.id_tipo_lavado'], ),
    sa.PrimaryKeyConstraint('id_historial')
    )
    op.create_index(op.f('ix_historial_lavado_id_historial'), 'historial_lavado', ['id_historial'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_lavado_id_historial'), table_name='historial_lavado')
    op.drop_table('historial_lavado')
    op.drop_index(op.f('ix_orden_servicio_id_orden'), table_name='orden_servicio')
    op.drop_table('orden_servicio')
    op.drop_index(op.f('ix_vehiculo_id_vehiculo'), table_name='vehiculo')
    op.drop_table('vehiculo')
    op.drop_index(op.f('ix_tipo_lavado_id_tipo_lavado'), table_name='tipo_lavado')
    op.drop_table('tipo_lavado')
    op.drop_index(op.f('ix_empleado_id_empleado'), table_name='empleado')
    op.drop_table('empleado')
    op.drop_index(op.f('ix_cliente_id_cliente'), table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
