"""Initial migration

Revision ID: eb90e0d6db55
Revises: 
Create Date: 2025-02-05 23:33:36.833253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb90e0d6db55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ordenes_servicio_id_orden', table_name='ordenes_servicio')
    op.drop_table('ordenes_servicio')
    op.drop_index('ix_empleados_id_empleado', table_name='empleados')
    op.drop_table('empleados')
    op.drop_index('ix_historial_lavado_id_historial', table_name='historial_lavado')
    op.drop_table('historial_lavado')
    op.drop_index('ix_clientes_id_cliente', table_name='clientes')
    op.drop_table('clientes')
    op.drop_index('ix_vehiculos_id_vehiculo', table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_index('ix_tipos_lavado_id_tipo_lavado', table_name='tipos_lavado')
    op.drop_table('tipos_lavado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_lavado',
    sa.Column('id_tipo_lavado', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('precio', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('duracion_estimada', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_lavado', name='tipos_lavado_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_tipos_lavado_id_tipo_lavado', 'tipos_lavado', ['id_tipo_lavado'], unique=False)
    op.create_table('vehiculos',
    sa.Column('id_vehiculo', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('placa', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('marca', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('modelo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tipo_vehiculo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id_cliente', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('total_lavados', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ultima_fecha_lavado', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], name='vehiculos_id_cliente_fkey'),
    sa.PrimaryKeyConstraint('id_vehiculo', name='vehiculos_pkey'),
    sa.UniqueConstraint('placa', name='vehiculos_placa_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_vehiculos_id_vehiculo', 'vehiculos', ['id_vehiculo'], unique=False)
    op.create_table('clientes',
    sa.Column('id_cliente', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('telefono', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cedula', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fecha_registro', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_cliente', name='clientes_pkey'),
    sa.UniqueConstraint('cedula', name='clientes_cedula_key'),
    sa.UniqueConstraint('email', name='clientes_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_clientes_id_cliente', 'clientes', ['id_cliente'], unique=False)
    op.create_table('historial_lavado',
    sa.Column('id_historial', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_orden', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id_tipo_lavado', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('fecha_lavado', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('observaciones', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estado_lavado', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_orden'], ['ordenes_servicio.id_orden'], name='historial_lavado_id_orden_fkey'),
    sa.ForeignKeyConstraint(['id_tipo_lavado'], ['tipos_lavado.id_tipo_lavado'], name='historial_lavado_id_tipo_lavado_fkey'),
    sa.PrimaryKeyConstraint('id_historial', name='historial_lavado_pkey')
    )
    op.create_index('ix_historial_lavado_id_historial', 'historial_lavado', ['id_historial'], unique=False)
    op.create_table('empleados',
    sa.Column('id_empleado', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_empleado', name='empleados_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_empleados_id_empleado', 'empleados', ['id_empleado'], unique=False)
    op.create_table('ordenes_servicio',
    sa.Column('id_orden', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_vehiculo', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id_empleado', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('fecha_orden', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_cobro', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id_empleado'], name='ordenes_servicio_id_empleado_fkey'),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id_vehiculo'], name='ordenes_servicio_id_vehiculo_fkey'),
    sa.PrimaryKeyConstraint('id_orden', name='ordenes_servicio_pkey')
    )
    op.create_index('ix_ordenes_servicio_id_orden', 'ordenes_servicio', ['id_orden'], unique=False)
    # ### end Alembic commands ###
